version: "3"

services:
  editor:
    image: httpd
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/
    ports:
      - "3000:80"

  api-php:
    build:
      context: ./engine/php
      dockerfile: Dockerfile.php
    ports:
      - 8080:80
    volumes:
      - ./htdocs:/var/www/html
    restart: always
